### ISSUE TITLE
Team support?

### ISSUE THREAD

**Issue by synth3tk** [djotaku/ELDonationTracker#1]
Any chance you can get team support put in by this year's gameday?

**Comment by djotaku** [comment]
I'll give it a shot.

**Comment by djotaku** [comment]
Working on it now. Adding team goal and team amount raised.

**Comment by djotaku** [comment]
Ok it's added. I'm closing the ticket. If there's something more specific you want related to teams, open a new ticket and I'll work on it.

Thanks and thanks for using the script!

**Comment by synth3tk** [comment]
Awesome! I'll check it out tomorrow.
