### ISSUE TITLE
team_id None generates errors.

### ISSUE THREAD

**Issue by Enochsoul** [djotaku/ELDonationTracker#128]
Installed via pypi, ran without participant.conf first time to get defaults from github, then edited my details in.  Set the team_id to None as per the docs as I'm not a member of a team, but doing this generates an error.  The intent is to run without the GUI, I'm just after the generated donation text files.

My participants.conf file:
```
{
"Version" : "2.0",

"extralife_id" : "413616",

"text_folder" : "/home/soulscode/ELTracker/",

"currency_symbol" : "$",

"team_id" : None,

"tracker_image": "/home/soulscode/ELTracker/TickThumbsup.gif",

"donation_sound": "/home/soulscode/ELTracker/goodmonkey.mp3",

"donors_to_display": "5",

"font_family": "Liberation Sans",

"font_size": 52,

"font_italic": true,

"font_bold": 75,

"font_color": [255, 255, 255, 255],

"tracker_background_color": [0, 255, 0, 255]

}
```

I get the following traceback error when running python3 -m eldonationtracker.participant:

```
(ELTracker) soulscode@Monolith2:~/.config/extralifedonationtracker$ python3 -m eldonationtracker.participant
Looking for persistent settings at /home/soulscode/.config/extralifedonationtracker
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/participant.py", line 287, in <module>
    participant_conf = extralife_io.ParticipantConf()
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/extralife_io.py", line 88, in __init__
    self.participantconf = self.load_json()
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/extralife_io.py", line 118, in load_json
    config = json.load(file)
  File "/usr/lib/python3.8/json/__init__.py", line 293, in load
    return loads(fp.read(),
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 10 column 13 (char 135)
```
The line 10 column 13 aligns with the value None in the team_id field.  If I remove the extra lines between elements in the JSON data the line/column follows.  If I replace None with the default quoted team ID, the config read seems to pass without issue.  I get other errors at this point, but that's probably a different issue I haven't chased down yet.

In case it matters, this is a fresh WSL Ubuntu install with Python 3.8.2 in a virtualenv set up only for eldonationtracker.

**Comment by djotaku** [comment]
Thanks for reporting. My smartphone died today so I'm trying to migrate to an old one. If I can, I'll get to today. If not, will be top priority tomorrow when I get home from work.

**Comment by djotaku** [comment]
It's looking extremely unlikely that I'll get to it tonight, but there are two things you can do for me that would help me determine if it's a regression or might give me a hint in where to start debugging tomorrow (or _maybe_ later tonight):

WSL is Linux on Windows, right? I haven't tested on that platform. Just regular Linux and regular Windows.

1. Would you be able to get the GUI for windows and try following the instructions there for no team and see if it errors out?

2. Would you be able to try GUI pypi install on Windows with a Windows install of Python (not the WSL)?

If either of those two work (or don't work) - that might help me to understand where the problem may lie.

At the very least, a quick check on my Linux computer (didn't clear out the Team because I don't have time to debug just yet) shows that it's working in general. And you mentioned having a different set of errors if you left my Team ID in there. 

Thanks! And thanks again for working with me to try and figure out the issue.

**Comment by Enochsoul** [comment]
I think I might have figured it out.  I don't think it's a code problem so much as a documentation problem.  It occurred to me that in Python, None is valid for no value, but for JSON the equivalent value is null.  Unquoted None in JSON is invalid. 

When I plug null in participant.conf as team_id it clears the same as a valid team ID.  Just to be paranoid, I confirmed that doing a JSON dump of a None value outputs null, and JSON load returns None from a null.  I also tried json load of a string with None as a value(intentionally malformed JSON data), and python returns the same JSON Decoder error above.

I did try the all in one EXE GUI application on Windows and it crashed, but not with the same error(Looks similar to the other error I'm getting in WSL Ubuntu after passing the participant.conf read).  Based on this, I'd guess that the GUI properly sets a blank team input as None, which takes us back to documentation. 8)

**Comment by Enochsoul** [comment]
From docs/participant_conf.rst line 67 is:

 - team_id:  if you're on a team, grab from team page URL. If not, put None without quotation marks

Should be:

 - team_id:  if you're on a team, grab from team page URL. If not, put null without quotation marks

Apologies, I'm not well versed enough with git to figure out how to propose the change that way.

**Comment by djotaku** [comment]
You are 100%  right. I could swear it used to be true at some point. Perhaps something about the way I changed things introduced this as a regression. Will get that fixed and put out a new release.

**Comment by djotaku** [comment]
OK. Fixed. Thanks for helping out make the documentation more accurate!
