### ISSUE TITLE
Crashing when outputting top donor details.

### ISSUE THREAD

**Issue by Enochsoul** [djotaku/ELDonationTracker#134]
Getting the following error in the Win32 version:

![image](https://user-images.githubusercontent.com/43549250/95027423-9531fc80-0655-11eb-8100-0ef5936f80bb.png)

and this from the linux CLI version:

```
 Couldn't access top donor data
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/participant.py", line 290, in <module>
    p.run()
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/participant.py", line 271, in run
    self.output_donor_data()
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/participant.py", line 241, in output_donor_data
    self._format_donor_information_for_output()
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/participant.py", line 177, in _format_donor_information_for_output
    self.donor_formatted_output['TopDonorNameAmnt'] = extralife_io.single_format(self.top_donor, False,
  File "/home/soulscode/virtualenvs/ELTracker/lib/python3.8/site-packages/eldonationtracker/extralife_io.py", line 303, in single_format
    return f"{donor.name} - {currency_symbol}{donor.amount:.2f}"
AttributeError: 'NoneType' object has no attribute 'name'
```

I suspect it's related to my top/only donor being anonymous.

Here's my participant.conf file from the CLI, the windows config should be identical:
```
{
"Version" : "2.0",

"extralife_id" : "413616",

"text_folder" : "/home/soulscode/ELTracker/",

"currency_symbol" : "$",

"team_id" : null,

"tracker_image": "/home/soulscode/ELTracker/TickThumbsup.gif",

"donation_sound": "/home/soulscode/ELTracker/goodmonkey.mp3",

"donors_to_display": "5",

"font_family": "Liberation Sans",

"font_size": 52,

"font_italic": true,

"font_bold": 75,

"font_color": [255, 255, 255, 255],

"tracker_background_color": [0, 255, 0, 255]

}
```

I'm running python 3.8.1 in Windows10, and 3.8.2 in a Ubuntu WSL(which in theory shouldn't be any different than normal Ubuntu for this application).

**Comment by djotaku** [comment]
Sorry for the delay. I'm pretty sure I know what the problem is. I will hopefully push out the fix tonight.

**Comment by djotaku** [comment]
Hmm, I thought I'd taken care of that, but I guess I have a corner case. You're good at finding those ;) I am starting my investigation now!

**Comment by djotaku** [comment]
Well, the problem is that the URL: https://www.extra-life.org/api/participants/413616/donors for you yields nothing...

**Comment by djotaku** [comment]
Oh, I think I (potentially) see the problem. You are the donor. So the donors page doesn't populate if it's just you.Except I appear on my donors page. So weird.....

**Comment by djotaku** [comment]
No, at least one person on the donor drive API room for discord says the donor endpoint behaves differently than the donations endpoint when it comes to anonymous donations. At least I know the direction for my fix now.

**Comment by djotaku** [comment]
OK, now that I know what was up, it's an easy fix. Getting ready to push to Github CI now

**Comment by djotaku** [comment]
OK, look for the 5.2.2 release in a few minutes!
