### ISSUE TITLE
Emojis in Name Break Tracker

### ISSUE THREAD

**Issue by Stumpyz** [djotaku/ELDonationTracker#137]
**Extra Life Participant ID and/or Team ID**
449362, although this is our new 2021 ID. We do not have access to the 2020 ID or API anymore unfortunately.

**GUI and/or Console**
Both, as far as I can tell, but I haven't verified the Console version.

**Describe the bug**
We had a donation from someone who has a four-leaf clover emoji in their name. As soon as it attempted to render the emoji, the software broke. I verified it was the emoji by clearing the name from the list with $1 donations. The same donor donated later, causing the software to break again.

**Error Output**
What, if anything, was output to the console when the error happened?

**To Reproduce**
1. Track any team in the GUI software.
2. Donate to the team via a mobile or emoji-capable device, being sure to add a four-leaf clover to the donor's name.
3. Observe the software freezing and crashing once the donation processes.
4. See error, if any pop.

**Expected behavior**
No crash and either the emoji or a missing emoji box rendering in the donations.

**Screenshots**
I would've gotten screenshots if we hadn't been mid-gameday at the time.

**Desktop (please complete the following information):**
 - OS: Windows 10 Pro
 - OS Version: 20H2, I want to say I was one update behind at time of the event/when the crash occurred.
 - Extra Life Donation Tracker Version: 5.2.3
 - Python Version: unknown, the PC was wiped between the time of crash and reporting the bug. Honestly forgot about reporting the bug until I was reviewing EL stats.

**Additional context**
As far as I can tell, it's just a lack of handling emojis. I can't tell if it's a client issue for not having an emoji library accessible, or if it's a software issue because there isn't an emoji library included. Either way, the issue can be fixed by listening for unknown unicode and just replacing it with a generic unicode box or something. Just a suggestion of course, I hope it helps.

**Comment by djotaku** [comment]
hey, I'm sorry it caused you problems on game day. 

I know I have some unit tests to cover writing emojis to the disk. 

I'm not entirely sure what would cause the issue with the donor names, but I'll see if I can write some unit tests to figure it out. 

Just to double-check that I understand what happened in your circumstance: Are you saying it crashed when it tried to show the emoji in the "you've got a donation" window? Or at some other point (that you can remember?)

**Comment by Stumpyz** [comment]
Hey, I totally understand. I had my own, much crappier API wrapper I wrote
that we were using before we found your software, and yours has been a HUGE
help.

It was crashing whenever the software did a pull on the API, because our
output file never received the donor's name. We never had it in a
notification either, so I think it was just the fact that it didn't
understand what an emoji was.

**Comment by djotaku** [comment]
OK, thanks for the kudos. I'll put it on the docket to try and figure out the problem this weekend. 

- First I'll see if I can recreate with unit tests. 
- Otherwise, I'll see if someone has emoji donors
- All else fails, I'll make an emoji donation myself

**Comment by djotaku** [comment]
couldn't find anything with my unit tests....

Both donors and donations are OK with 4-leaf clovers in the names. Next up to see if someone else has emojis in donor names.

**Comment by djotaku** [comment]
I believe I have tracked down the issue to loading into the GUI on Windows. And maybe even writing to the file. I thought I'd solved an issue like this before, but I guess it has resurfaced. Time to debug....
