### ISSUE TITLE
Donation Total Being Above $1,000 Causes ValueError

### ISSUE THREAD

**Issue by Stumpyz** [djotaku/ELDonationTracker#169]
**Extra Life Participant ID and/or Team ID**
Participant: 449362
Team: 55953

**GUI and/or Console**
Both

**Describe the bug**
As soon as we went above $1,000, the software started crashing. I looked at the console window, and it seems that there is a comma causing the conversion call to error out.

**Error Output**
line 518, in run
line 439, output_donation_data
line 428, _check_existence_of_text_files
ValueError: could not convert string to float: '1,155.00'
**To Reproduce**
Enter our participation data into the software, click Run, watch the console window as it crashes

**Expected behavior**

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/76961960/130335182-39171baa-cb06-4338-8298-2a1bf6ec1e21.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version 20H2
 - Extra Life Donation Tracker Version 6.2.1
 - Python Version

**Additional context**

**Comment by djotaku** [comment]
Well, I will get right on that!
