### ISSUE TITLE
Application unable to connect to the EL API.

### ISSUE THREAD

**Issue by Enochsoul** [djotaku/ELDonationTracker#199]
**Extra Life Participant ID and/or Team ID**
499883

**GUI and/or Console**
GUI

**Describe the bug**
Application apparently unable to access Extra Life API, returns error that it cannot reach EL API participant endpoint.

**Error Output**
Returns error in the GUI when trying to validate new Participant ID: "Could not reach https://www.extra-life.org/api/participants/499883. Participant ID may be invalid."

Also seeing the following in the console window after a few seconds when I click Run.

```
[10/13/22 10:05:35] ERROR    ExtraLife IO: Error with JSON response.
                    ERROR    ExtraLife IO: The request status code was 429 from
                             url='https://www.extra-life.org/api/participants/499883?version=1.2'
                    WARNING  Participant: Couldn't access participant JSON.
                    ERROR    ExtraLife IO: Error with JSON response.
                    ERROR    ExtraLife IO: The request status code was 429 from
                             url='https://www.extra-life.org/api/participants/499883/incentives?version=1.2'
                    INFO     ExtraLife IO:  totalRaised.txt doesn't exist. This is OK if this is your first run.
                    INFO     Participant: No donations, writing default data to files.
[10/13/22 10:05:38] ERROR    ExtraLife IO: Error with JSON response.
                    ERROR    ExtraLife IO: The request status code was 429 from
                             url='https://www.extra-life.org/api/participants/499883/badges?version=1.2'
                    ERROR    ExtraLife IO: Error with JSON response.
                    ERROR    ExtraLife IO: The request status code was 429 from
                             url='https://www.extra-life.org/api/participants/499883/milestones?version=1.2'
                    ERROR    ExtraLife IO: Error with JSON response.
                    ERROR    ExtraLife IO: The request status code was 429 from
                             url='https://www.extra-life.org/api/teams/62462?version=1.2'
                    WARNING  Team:: Could not get team JSON
[10/13/22 10:05:39] ERROR    ExtraLife IO: Error with JSON response.
                    ERROR    ExtraLife IO: The request status code was 429 from
                             url='https://www.extra-life.org/api/teams/62462/badges?version=1.2'
                    INFO     Participant: Finished checking API and updating text files!
```

**To Reproduce**
1) Download newest EXE file.
2) Open file, update Participant ID in settings.
3) Click Run.

**Expected behavior**
Expect application to poll Extra Life API and retrieve participant details.

**Screenshots**
![image](https://user-images.githubusercontent.com/43549250/195693404-35defe9c-9bf1-4fe9-9d3b-7893de935cdd.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - OS Windows 10
 - Extra Life Donation Tracker Version: 7.4.8, 7.4.7 and 7.0.2(I know, ancient) of the compiled EXE do the same thing.
 - Python Version: N/A

**Additional context**
The API URL works fine when copied into a new private browser window in Firefox, which would imply that there's no networking issues between my computer and the EL API, as well as validating that my participant ID is correct.  The only change I made was to download the new version EXE file, and update my participant ID within the configuration.  The application recognized the config from the persistent location, and maintained all other settings.  I also tried to rename the participant.conf file and start up again with a fresh config, but got the same results.  On a whim I started up the version I used from last year(7.0.2) and got the exact same thing, which in theory shouldn't be possible since it worked fine last year, unless there's some range or length issue with the participant ID.

**Comment by Enochsoul** [comment]
I cloned the repo and ran it directly instead of via the precompiled EXE, and I get the same result.  I also did some more digging, and noticed on the EL Discord that this had come up earlier in the year.  I see yourself and a couple others discussing it with the Donor Drive people, but I wasn't able to find a resolution in the chat history.

I also noticed that when I use other browsers, sometimes for the first call with a new browser(IE not one in a window that's logged into EL), I do occasionally get the same error in the browser.  Since the I've messed with a few things that might have added to the IP block, I'm going to go hands off for a few hours and see if any block that might be on my IP gets cleared.

**Comment by djotaku** [comment]
It's working for me, so let me know after tomorrow. I had another person with the same issue (what you saw in Discord) and it started working again for them after a day or two. This whole rate-limiting thing has been a real pain since a couple years ago with the Game Day DDOS. 

Also, thanks, as usual, for a well-documented bug report.

**Comment by Enochsoul** [comment]
Checked again today, and no issues, everything worked as expected.  So there is definitely a clear timer on the IP block, but it must be several hours.  Apologies for the non-bug submission.
