### ISSUE TITLE
Team Stats not updating.

### ISSUE THREAD

**Issue by brandorf** [djotaku/ELDonationTracker#201]
I'm using the latest windows build.  My team stats don't seem to update at all.  The UI for team info remains blank, and the relevant text files don't update.

![image](https://user-images.githubusercontent.com/4810925/199868946-6054f5b6-1151-414d-9489-bba1787d8f31.png)
![image](https://user-images.githubusercontent.com/4810925/199868976-f7b19b55-bf0a-4b7a-ae88-dda1658097ff.png)

**Comment by djotaku** [comment]
I'm sorry that I didn't see this before EL day this weekend. Thanks for reporting - I'll check it out
