### ISSUE TITLE
Errors when trying to launch Windows executable (console and GUI).

### ISSUE THREAD

**Issue by chriscarter79** [djotaku/ELDonationTracker#212]
**Extra Life Participant ID and/or Team ID**
522967

**GUI and/or Console**
Both

**Describe the bug**
Receive error message when launching app in console. Receive error message in GUI when validating participant ID. 

**Error Output**
Console error:
[11/07/23 15:59:34] INFO     ExtraLife IO: Looking for persistent settings at
                             C:\Users\mrd1sturbed\AppData\Roaming\config\extralifedonationtracker
                    INFO     ExtraLife IO: Persistent settings found.
QPixmap::scaleHeight: Pixmap is a null pixmap
DirectShowPlayerService::doSetUrlSource: Unresolved error code 0x80070003 (The system cannot find the path specified.)

GUI error:
Could not reach https://www.extra-life.org/api/participants/522967. Participant ID may be invalid.

**To Reproduce**
1. Launch app
2. Click on 'settings'
3. Input '522967' in participant ID
4. Click on 'Validate Participant ID'
5. See error

**Expected behavior**
Participant ID should be validated, and txt files should be generated to the specified output folder.

**Screenshots**
![Screenshot 2023-11-07 160833](https://github.com/djotaku/ELDonationTracker/assets/1871729/81133f4f-511c-4204-9bac-78c7cecf374f)

![Screenshot 2023-11-07 160631](https://github.com/djotaku/ELDonationTracker/assets/1871729/e6df9c5c-b4e4-4b4b-8dd5-437402f4f95d)

**Desktop (please complete the following information):**
 - OS: Windows 11 
 - OS Version 22H2 (22621.2506)
 - 7.5.0
 - Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32

**Additional context**
I have tested the API endpoint using Postman and I am able to get a return payload. 
{
    "fundraisingGoal": 500.00,
    "eventName": "Extra Life 2023",
    "links": {
        "donate": "https://www.extra-life.org/index.cfm?fuseaction=donorDrive.participant&participantID=522967#donate",
        "page": "https://www.extra-life.org/index.cfm?fuseaction=donorDrive.participant&participantID=522967"
    },
    "hasActivityTracking": false,
    "role": "I",
    "participantID": 522967,
    "numIncentives": 0,
    "isCustomAvatarImage": true,
    "displayName": "Christopher Carter",
    "sumDonations": 0.00,
    "eventID": 553,
    "createdDateUTC": "2023-10-16T21:10:45.187+0000",
    "numMilestones": 0,
    "participantTypeCode": "I",
    "avatarImageURL": "https://assets.donordrive.com/extralife/images/$avatars$/constituent_3B8FDB00-C293-34EB-49BEB7A754201390.jpg",
    "sumPledges": 0.00,
    "numDonations": 0
}

**Comment by djotaku** [comment]
thanks for reporting. I'll take a look

**Comment by djotaku** [comment]
Works for me... did you have a space or anything in your number when you put it in?

**Comment by chriscarter79** [comment]
I used it this weekend and it worked again. Must have been something down on the Twitch end. Thanks for checking into it though, and great work on the app it was very helpful.

**Comment by djotaku** [comment]
glad it ended up working. Happy it was helpful for you!
