### ISSUE TITLE
KeyError: 'displayName'

### ISSUE THREAD

**Issue by Enochsoul** [djotaku/ELDonationTracker#40]
I'm not sure if it's me or not, but I'm getting the following error when trying to run the extralifedonations.py, both via the gui.py or directly.

Traceback (most recent call last):
  File "extralifedonations.py", line 179, in <module>
    p.run()
  File "extralifedonations.py", line 154, in run
    self.get_donors()
  File "extralifedonations.py", line 101, in get_donors
    self.donorlist = [Donor(self.donorJSON[donor]['displayName'], self.donorJSON[donor].get('message'), self.donorJSON[donor]['amount']) for donor in range(0, len(self.donorJSON))]
  File "extralifedonations.py", line 101, in <listcomp>
    self.donorlist = [Donor(self.donorJSON[donor]['displayName'], self.donorJSON[donor].get('message'), self.donorJSON[donor]['amount']) for donor in range(0, len(self.donorJSON))]
KeyError: 'displayName'

It worked fine a couple of weeks ago, but it's throwing this tonight after I updated to your newest release.  I updated Python to 3.7.5(I had 3.7.4 before)as well just to be sure, but I get the same error.

I did try to chase down the issue, but unfortunately my python skills aren't up to this yet.

**Comment by djotaku** [comment]
I'm pretty sure I know both the cause and solution. I can't work on it until later tonight. In the meanwhile - can you post your extra life ID so I can test it when I've come up with a fix?

**Comment by Enochsoul** [comment]
My EL id is 366732.

**Comment by djotaku** [comment]
Thanks! I'm going to tackle it now. With luck I'll have something out within the hour. (Watching my children right now, so they may cause some delays/distractions)

**Comment by djotaku** [comment]
Are you using v2.2? This is exactly the problem I fixed there. And with v2.2 I am not getting errors.

**Comment by Enochsoul** [comment]
I thought I was.  I just did a manual download of the windows build instead of going through git for the sources and it seems to work now.  I probably messed up the git update, thanks so much for your responsiveness.

**Comment by Enochsoul** [comment]
Unrelated to this issue, though it works, I get the following error:

Starting Thread-1
Couldn't get to team URL.
                Check team ID.
                Or server may be unavailable.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "gui.py", line 111, in run
  File "extralifedonations.py", line 176, in run
  File "team.py", line 113, in team_run
  File "team.py", line 25, in get_team_json
AttributeError: 'Team' object has no attribute 'team_json'

Regardless of if I have a team configured or not, though everything still works.  This is from a fresh install from the zip archive.

**Comment by djotaku** [comment]
would you be OK opening this in another issue to keep like issues together? I'll take a look at it later tonight.

**Comment by Enochsoul** [comment]
No sooner done than said.
