### ISSUE TITLE
Windows build throwing error about Teams

### ISSUE THREAD

**Issue by Enochsoul** [djotaku/ELDonationTracker#41]
**Extra Life Participant ID and/or Team ID**
This will help me figure out if I've fixed your issue. 

**GUI and/or Console**
Does the bug only happen on the GUI? Console? both?
Both, though running the GUI allows everything to continue working, running on the console causes it to crash out on the error.

**Describe the bug**
Throws an error regardless of team status.

**Error Output**
Starting Thread-1
Couldn't get to team URL.
Check team ID.
Or server may be unavailable.
Exception in thread Thread-1:
Traceback (most recent call last):
File "threading.py", line 926, in _bootstrap_inner
File "gui.py", line 111, in run
File "extralifedonations.py", line 176, in run
File "team.py", line 113, in team_run
File "team.py", line 25, in get_team_json
AttributeError: 'Team' object has no attribute 'team_json'

**To Reproduce**
Running the GUI.exe or the extralifedonations.py generates the error.  Has been tested by wiping total local contents of folder, replacing from downloaded archive and configuring from GUI.

**Desktop (please complete the following information):**
 - OS: Win10
 - Extra Life Donation Tracker Version: 2.2
 - Python Version: 3.7

**Additional context**

**Comment by djotaku** [comment]
Thanks for opening a new issue and thanks for following the template! You're an awesome user.

I'm not able to replicate your issue, so I'm curious - did you copy your participant.conf over? Or start fresh? I looked at your page and you're not part of a team (as far as I can tell). So I started fresh with just your user ID and the only thing I'm seeing (that I'm not going to risk breaking something by trying to fix before game day) is that the GUI Error: repeats over and over, but I'm not getting that exception that you're seeing. 

If you open up your participant.conf file (notepad should be fine) - what does it show by "TeamID"? It should look like:

"TeamID":null

Is that what you see?

**Comment by djotaku** [comment]
@Enochsoul let me know if you have an answer to above. Otherwise I'm going to have to close this one because I can't duplicate the issue on my end.

**Comment by Enochsoul** [comment]
Sorry for not responding, the week leading up to game day was a mess.  I think you can close this, after messing with it a bunch more it might be a PEBKAC.  I typed null in the team field instead of leaving it blank, which got me a "null" in the config file instead of null, which obviously wasn't working.  

Thanks again for making/maintaining this tool, and being a responsive dev.

**Comment by djotaku** [comment]
Ok, thanks. Closing.
