### ISSUE TITLE
Couldn't get to participant URL

### ISSUE THREAD

**Issue by McSquid** [djotaku/ELDonationTracker#43]
**Extra Life Participant ID and/or Team ID**
This will help me figure out if I've fixed your issue. 
349598

**GUI and/or Console**
Does the bug only happen on the GUI? Console? both?
Only GUI tested

**Describe the bug**
When clicking run, Nothing happens, and console shows "Couldn't get to participant URL."

**Error Output**
What, if anything, was output to the console when the error happened?
"
run button
Starting Thread-1
Couldn't get to participant URL
     Check ExtraLifeID.
     Or server may be unavailable.
Exception in thread Thread-1:
 File "Threading.py", line 926, in _bootstrap_inner
 File "gui.py", line 111, in run
 File "extralifedonations.py", line 168, in run
 File "extralifedonations.py", line 82, in get_participant_JSON
AttributeError: 'Participant' object has no attribute 'participantJSON'

**To Reproduce**
1. Extract Extra.Life.Donation.Tracker.for.Windows.v2.2.1.zip
2. Run gui.exe
3. Click settings, enter EL ID, clear team id
4. Click save
5. Click run
6. Observe error in console

**Expected behavior**
Gui to populate with EL information and data

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version [e.g. 22]
 - Extra Life Donation Tracker Version
 - Python Version 3.8

**Additional context**

**Comment by McSquid** [comment]
I tried a fresh install and did not change the default values (EL and team IDS) and got the same issue. 
I have also verified that nothing is being blocked by a firewall or antivirus.

**Comment by djotaku** [comment]
OK I'll take a look later today

**Comment by djotaku** [comment]
Apparently my program isn't the only one affected - Python apps are currently getting 403s

**Comment by djotaku** [comment]
Working with the guys who run the API to see what's up

**Comment by McSquid** [comment]
Huh... Glad to see it wasn't just me being stupid. Thanks!

**Comment by djotaku** [comment]
Fixed with #44 - go ahead and grab the v2.2.2 release and it should work now. Tested with my participantID and teamID and it worked on Windows and Linux.
