### ISSUE TITLE
last5DonorNameAmtsHorizontal?

### ISSUE THREAD

**Issue by McSquid** [djotaku/ELDonationTracker#45]
Any chance you could add last5DonorNameAmtsHorizontal (Without message) as a text file?

**Comment by djotaku** [comment]
CAAAAAAAAAAAAAN DO! 

![something](https://media.giphy.com/media/eMstc0q4Jh9tavfvKs/giphy.gif)

**Comment by djotaku** [comment]
ok, handled with #46 - head to releases and grab v2.2.3
