### ISSUE TITLE
KeyError: 'amount'

### ISSUE THREAD

**Issue by sistakaren** [djotaku/ELDonationTracker#50]
Hi!  Thank you for making this, it's been really great!  However, of late, I haven't been able to get recent donations or last donation fields to work at all and it's been giving me an error that says "KeyError: 'amount'", and I can't figure it out.  You can see in the screenshots below...

**Extra Life Participant ID and/or Team ID**
385304

**GUI and/or Console**
Both!

**Describe the bug**
When I run the program, it will get most of the data except the data about "recent donations" and "last donations".  And it returns this error that says: KeyError: 'amount' and it won't populate the text files.

**Error Output**
What, if anything, was output to the console when the error happened?

"Exception in thread Thread-1:
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "gui.py", line 163, in run
  File "extralifedonations.py", line 136, in run
  File "extralifedonations.py", line 102, in get_donors
  File "extralifedonations.py", line 102, in <listcomp>
KeyError: 'amount'"

**To Reproduce**
I just run the program with my user ID and that's what happens.

**Expected behavior**
I expected this error to not occur and to see my last donations and recent donations.

**Screenshots**

My settings (forgive the blue mark!):
![image](https://user-images.githubusercontent.com/54153161/71311147-ec2e5400-23ea-11ea-9a78-61999bdbb108.png)

What the GUI looks like after I hit "run" (see nothing in the last and recent donations):
![image](https://user-images.githubusercontent.com/54153161/71311161-2dbeff00-23eb-11ea-871e-df9ab57011a1.png)

Console output: 
![image](https://user-images.githubusercontent.com/54153161/71311153-0831f580-23eb-11ea-8287-d3820e954499.png)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - OS Version 1903 
 - Extra Life Donation Tracker Version: 3.0
 - Python Version: ?

**Additional context**
I tried to delete the persistent settings to see if it would help, but it didn't.  Definitely at a loss.  Thanks so much!

**Comment by djotaku** [comment]
OK, I'll take a look in a bit

**Comment by djotaku** [comment]
hehe. Looks like you found a corner case of some sort for me. In other words, works for my Extra Life ID and yours gives the error you mention above. I'm on the case. BTW - thanks for being thorough and including screenshots!

**Comment by djotaku** [comment]
I'm guessing it's the Anonymous donors screwing things up. I'm pretty sure I know how to fix. Hopefully something to you in 15 minutes or less.

**Comment by djotaku** [comment]
OK, look for release 3.1 in the next couple minutes. That fixes it!

**Comment by sistakaren** [comment]
Whoa that's so neat-- i was super convinced I was doing something wrong.  Thank you so much!

**Comment by sistakaren** [comment]
Also it works! Thanks again!!
